config/routes.rb
Rails.application.routes.draw do
  # verb '/path', to: 'controller#action', as: :prefix
  # the prefix ONLY refers to the path, not the http verb
  # get '/restaurants/top', to: 'restaurants#top', as: :top_restaurants

  resources :restaurants do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
end

# collection -> when it's about all restaurants (aka no id)
# member -> when it's about one specific restaurant (aka need an id)
# collection do
#   get :top
# end
# member do
#   get :chef
# end

# restaurant = Restaurant.find(this needs to come from the params)
# review.restaurant = restaurant
# we need the restaurant's id in our new/create routes

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # associations
  has_many :reviews # creates a method -> restaurant.reviews
  # validations
  validates :name, presence: true
  validates :address, presence: true

  def avg_rating
    return unless reviews.any?

    reviews.average(:rating).round
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant # creates a method -> review.restaurant
  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    # this empty instance is for the form generator
    @restaurant = Restaurant.new
    # render 'new.html.erb'
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      # show the form again if validations failed
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # this instance is for the form generator
    # render 'edit.html.erb'
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    # Strong params -> we are filtering the attributes from the form
    # {"name"=>"Sukiya", "address"=>"Meguro", "rating"=>"2"}
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    
    respond_to do |format| # format will be html, json, csv, etc.
      if @review.save
        # We handle each response format differently
        format.html { redirect_to restaurant_path(@restaurant) } # standard behaviour that we want to keep
        format.json # by default, it looks for a reviews/create.json.jbuilder # jbuilder is the equivalent of ERB for JSON
      else
        format.html { render :new, status: :unprocessable_entity } # standard behaviour that we want to keep
        format.json
      end
    end
  end

  # # REMINDER: when we don't specify `render` or `redirect_to` at the end of an action
  # def show
  #   @review = Review.find(params[:id])

  #   # render :show # by default, looks for a reviews/show.html.erb file to render
  # end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheChopsticks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://source.unsplash.com/featured/?<%= restaurant.category.downcase %>&<%= rand(1000) %>)">
  <%= restaurant.name %>
  <%= link_to "", restaurant_path(restaurant), class: "card-link"  %>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/_side_info.html.erb
<p class="fw-lighter opacity-75">
  <i class="fas fa-map-pin"></i><span class='ms-2'><%= @restaurant.address %></span>
</p>
<p class="fw-lighter opacity-75">
  <% rand(2..5).times do %>
    <i class="fas fa-dollar-sign"></i>
  <% end %>
</p>
<p class="fw-lighter opacity-75">
  <i class="fas fa-utensils"></i><span class='ms-2'><%= @restaurant.category %></span>
</p>
<div class="d-flex">
  <%= link_to edit_restaurant_path(@restaurant) do %>
    <i class="fas fa-pencil-alt btn-light mx-1"></i>
  <% end %>
  <%= link_to restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Do you want to delete #{@restaurant.name}" } do %>
    <i class="fas fa-trash btn-light mx-1"></i>
  <% end %>
</div>

app/views/restaurants/chef.html.erb
<div class="container mt-3">
  <h1><%= @restaurant.chef_name %></h1>
  <p><%= link_to @restaurant.name, restaurant_path(@restaurant) %></p>
</div>

app/views/restaurants/edit.html.erb
<div class="container mt-3">
  <h1>Update Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>Restaurants</h1>
    <%= link_to new_restaurant_path do %>
      <i class="fas fa-plus-square btn-light"></i>
    <% end %>
  </div>
  <div class="cards mb-5">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-3">
  <h1>Add a Restaurant</h1>
  <%= render 'restaurants/form' %>
</div>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://source.unsplash.com/featured/?<%= @restaurant.category.downcase %>&<%= rand(1000) %>/800x333);">
  <div class="container"></div>
</div>
<div class="container mt-2">
  <div class="row justify-content-around">
    <div class="col-12 col-sm-8">
      <p>
        <%= link_to '< Restaurants', restaurants_path, class: 'btn-light opacity-25 text-decoration-none' %>
      </p>
      <div class="d-flex align-items-center">
        <h1 class="m-0"><%= @restaurant.name %></h1>
        <p class="m-0 ms-2" style="font-size: 0.8em">
          <% if @restaurant.avg_rating %>
            <%= render 'reviews/stars', rating: @restaurant.avg_rating %>
          <% else %>
            No ratings yet
          <% end %>
        </p>
      </div>
      <p class="fw-lighter opacity-75 mt-2"><%= @restaurant.description  %></p>
      <h3>Reviews</h3>
      <div data-controller="insert-in-list">
        <%= render 'reviews/form', restaurant: @restaurant, review: @review %>
        <ul data-insert-in-list-target="itemsList">
          <% if @restaurant.reviews.any? %>
            <%= render @restaurant.reviews.order(created_at: :desc) %>
          <% else %>
            <li>No reviews yet</li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-12 col-sm-4 mt-5">
      <%= render 'restaurants/side_info' %>
    </p>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1>Top Restaurants</h1>
    <%= link_to new_restaurant_path do %>
      <i class="fas fa-plus-square btn-light"></i>
    <% end %>
  </div>
  <div class="cards mb-5">
    <% @restaurants.each do |restaurant| %>
      <%= render 'restaurants/card', restaurant: restaurant %>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%# <div data-action="event->controller-name#action"></div> %>
<%#= image_tag url, data: { action: "event->controller-name#action" } %>
<%= simple_form_for [restaurant, review], html: {
  data: {
    action: "submit->insert-in-list#submit"
  }
} do |f| %>
  <div class="star-rating mb-4">
    <% 5.times do |i| %>
      <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
  <%= f.input :content, label: false %>
  <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/reviews/_review.html.erb
<div class="p-3 text-center">
  <%= render 'reviews/stars', rating: review.rating %>
  <p><i class="fa-solid fa-quote-left"></i> <%= review.content %></p>
  <p><small><%= time_ago_in_words(review.created_at) %> ago</small></p>
</div>

app/views/reviews/_stars.html.erb
<% rating.times do %>
  <i class="fas fa-star"></i>
<% end %>
<% (5 - rating).times do %>
  <i class="far fa-star"></i>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/dmbf29", class: "avatar" %>
        </li>
      </ul>
    </div>
  </div>
</div>